-- begin SHOPWITHCUBA_PRODUCT
create table SHOPWITHCUBA_PRODUCT (
    ID bigint generated by default as identity(start with 1) not null,
    UUID varchar(36),
    --
    NAME varchar(255) not null,
    PRICE integer not null,
    --
    primary key (ID)
)^
-- end SHOPWITHCUBA_PRODUCT
-- begin SHOPWITHCUBA_CLIENT
create table SHOPWITHCUBA_CLIENT (
    ID bigint generated by default as identity(start with 1) not null,
    UUID varchar(36),
    --
    FULL_NAME varchar(255) not null,
    PHONE_NUMBER varchar(255) not null,
    EMAIL varchar(255) not null,
    DISCOUNT integer,
    --
    primary key (ID)
)^
-- end SHOPWITHCUBA_CLIENT
-- begin SHOPWITHCUBA_ORDER
create table SHOPWITHCUBA_ORDER (
    ID bigint generated by default as identity(start with 1) not null,
    UUID varchar(36),
    --
    NUMBER_ORDER varchar(255) not null,
    CLIENT_ID bigint not null,
    PRICE integer,
    --
    primary key (ID)
)^
-- end SHOPWITHCUBA_ORDER
-- begin SHOPWITHCUBA_ORDER_ITEM
create table SHOPWITHCUBA_ORDER_ITEM (
    ID bigint generated by default as identity(start with 1) not null,
    UUID varchar(36),
    --
    PRODUCT_ID bigint not null,
    COUNTER integer not null,
    NUMBER_ORDER_ID bigint not null,
    --
    primary key (ID)
)^
-- end SHOPWITHCUBA_ORDER_ITEM
