-- begin SHOPWITHCUBA_CLIENT
create unique index IDX_SHOPWITHCUBA_CLIENT_UNIQ_EMAIL on SHOPWITHCUBA_CLIENT (EMAIL) ^
create unique index IDX_SHOPWITHCUBA_CLIENT_UNIQ_PHONE_NUMBER on SHOPWITHCUBA_CLIENT (PHONE_NUMBER) ^
-- end SHOPWITHCUBA_CLIENT
-- begin SHOPWITHCUBA_ORDER
alter table SHOPWITHCUBA_ORDER add constraint FK_SHOPWITHCUBA_ORDER_ON_CLIENT foreign key (CLIENT_ID) references SHOPWITHCUBA_CLIENT(ID)^
create unique index IDX_SHOPWITHCUBA_ORDER_UNIQ_NUMBER_ORDER on SHOPWITHCUBA_ORDER (NUMBER_ORDER) ^
create index IDX_SHOPWITHCUBA_ORDER_ON_CLIENT on SHOPWITHCUBA_ORDER (CLIENT_ID)^
-- end SHOPWITHCUBA_ORDER
-- begin SHOPWITHCUBA_ORDER_ITEM
alter table SHOPWITHCUBA_ORDER_ITEM add constraint FK_SHOPWITHCUBA_ORDER_ITEM_ON_PRODUCT foreign key (PRODUCT_ID) references SHOPWITHCUBA_PRODUCT(ID)^
alter table SHOPWITHCUBA_ORDER_ITEM add constraint FK_SHOPWITHCUBA_ORDER_ITEM_ON_NUMBER_ORDER foreign key (NUMBER_ORDER_ID) references SHOPWITHCUBA_ORDER(ID) on delete CASCADE^
create index IDX_SHOPWITHCUBA_ORDER_ITEM_ON_PRODUCT on SHOPWITHCUBA_ORDER_ITEM (PRODUCT_ID)^
create index IDX_SHOPWITHCUBA_ORDER_ITEM_ON_NUMBER_ORDER on SHOPWITHCUBA_ORDER_ITEM (NUMBER_ORDER_ID)^
-- end SHOPWITHCUBA_ORDER_ITEM
